services:

    database:
      image: postgres
      ports:
        - 5432:5432
      restart: always

      environment:
        POSTGRES_USER: son
        POSTGRES_PASSWORD: nos
        POSTGRES_DB: jobDB
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - 80:80
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: son

